### ISSUE TITLE
Requirements Document

### ISSUE THREAD

**Issue by ovvioinfame233** [Team-Trimble/Trimble#3]
This document is a requirments document. This outlines all we need to in accordance with our project goal. This includes but is not limited to [non]functional objectives, context and use case model, and background.

**Comment by ovvioinfame233** [comment]
Made the Due Date 10/19 - as of now, subject to change

**Comment by KyleRosenberg** [comment]
My Card: https://app.gitkraken.com/glo/board/XYVEwJY11wAPYp7N/card/XbomzNnTpQAP1zXc
