### ISSUE TITLE
Project Charter

### ISSUE THREAD

**Issue by ovvioinfame233** [Team-Trimble/Trimble#4]
This is our project charter that we have been working on with our sponser. This includes a scope (in and out) of our project, along with roles, responibilies, and deliverables.

**Comment by ovvioinfame233** [comment]
Due date is 10/12 - Due Friday according to Moodle

**Comment by KyleRosenberg** [comment]
DeVonte sent back a signed first page so we'll just have to combine it with the rest
https://drive.google.com/open?id=0B4tjwwgmCnGUdVl1NHl4b2t2WnBWOVNsNmloWUxhbkxsWERR
